"""
Pydantic schemas for FitPath ADK multi-agent workflow.

Security: no guest tokens, auth headers, raw notes, or DB handles are defined here.
Only sanitised, validated profile fields flow from FastAPI into the workflow.
"""
from __future__ import annotations

import math
from typing import Optional
from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Workflow Input (FastAPI → Workflow boundary — sanitised profile only)
# ---------------------------------------------------------------------------

class WorkflowInput(BaseModel):
    """Sanitised profile fields only. Built from stored DB profile, never from
    raw client request bodies.  No tokens, hashes, or raw notes."""
    goal: str
    fitness_level: str
    duration_days: int          # 30 | 60 | 90
    available_time_mins: int
    days_per_week: int
    equipment: list[str]        # e.g. ["Dumbbells", "Yoga mat"]
    preferred_days: list[str]   # e.g. ["Monday", "Wednesday", "Friday"]
    safety_status: str          # "safe" | "general_fitness_redirect" | "medical_review_required"
    safety_message: str


# ---------------------------------------------------------------------------
# Intake Agent Output
# ---------------------------------------------------------------------------

class AgentFitnessContext(BaseModel):
    """Enriched fitness context derived by the Intake Agent from WorkflowInput."""
    goal: str
    fitness_level: str
    duration_days: int
    total_weeks: int            # = ceil(duration_days / 7)
    available_time_mins: int
    days_per_week: int
    equipment: list[str]
    preferred_days: list[str]
    focus_tags: list[str]       # derived: e.g. ["stamina", "mobility"]


# ---------------------------------------------------------------------------
# Safety Guidance Agent Output
# ---------------------------------------------------------------------------

class SafetyGuidanceResponse(BaseModel):
    """Supportive explanation of the safety screening result."""
    safety_status: str
    title: str
    message: str
    can_proceed: bool


# ---------------------------------------------------------------------------
# Draft Plan Schemas  (Plan Generator output — LLM selects exercise structure only)
# instructions, safety_note, and equipment are NOT generated by the LLM.
# ---------------------------------------------------------------------------

class DraftWorkoutExercise(BaseModel):
    """What the Plan Generator LLM is allowed to produce for each exercise."""
    name: str                       # Must match a catalog exercise name exactly
    duration_mins: int | None = None
    sets: Optional[int] = None
    reps: Optional[int] = None


class DraftWorkoutDay(BaseModel):
    day: str                        # "Monday" | "Tuesday" ... | "Rest"
    is_rest: bool
    focus: str
    exercises: list[DraftWorkoutExercise]


class DraftWeeklyPlan(BaseModel):
    week_number: int = Field(ge=1)
    days: list[DraftWorkoutDay]


class FitnessRoadmap(BaseModel):
    """High-level roadmap.  duration_days and total_weeks are validated against
    the stored profile by the final validator."""
    duration_days: int              # Must equal profile.duration_days
    total_weeks: int                # Must equal ceil(duration_days / 7)
    phase_summaries: list[str]      # One entry per 4-week phase
    progression_notes: str

    @model_validator(mode="after")
    def check_total_weeks(self) -> "FitnessRoadmap":
        expected = math.ceil(self.duration_days / 7)
        if self.total_weeks != expected:
            raise ValueError(
                f"total_weeks ({self.total_weeks}) must equal "
                f"ceil({self.duration_days}/7) = {expected}"
            )
        return self


class DraftGeneratedFitnessPlan(BaseModel):
    """Full output of the Plan Generator LLM.  Uses draft exercises."""
    roadmap: FitnessRoadmap
    week_1: DraftWeeklyPlan


# ---------------------------------------------------------------------------
# Enriched Plan Schemas  (after plan_normalizer.py runs)
# instructions and safety_note come from exercises.json, not from the LLM.
# ---------------------------------------------------------------------------

class EnrichedWorkoutExercise(BaseModel):
    """Exercise enriched by the deterministic normalizer from the catalog."""
    name: str
    duration_mins: int
    sets: Optional[int] = None
    reps: Optional[int] = None
    instructions: list[str]         # From exercises.json catalog
    safety_note: str                # From exercises.json catalog
    required_equipment: list[str]   # Canonical values from exercises.json


class EnrichedWorkoutDay(BaseModel):
    day: str
    is_rest: bool
    focus: str
    exercises: list[EnrichedWorkoutExercise]
    total_duration_mins: int        # Sum of exercise duration_mins


class EnrichedWeeklyPlan(BaseModel):
    week_number: int
    days: list[EnrichedWorkoutDay]


class GeneratedFitnessPlan(BaseModel):
    """Final enriched plan — roadmap + Week 1 with full exercise details."""
    roadmap: FitnessRoadmap
    week_1: EnrichedWeeklyPlan


# ---------------------------------------------------------------------------
# Plan Reviewer Output
# ---------------------------------------------------------------------------

class PlanReviewResult(BaseModel):
    passed: bool
    violations: list[str]
    approved_plan: Optional[GeneratedFitnessPlan] = None


# ---------------------------------------------------------------------------
# Progress Coach (Check-in)
# ---------------------------------------------------------------------------

class CheckInInput(BaseModel):
    completed_sessions: int = Field(ge=0)
    energy_level: int = Field(ge=1, le=5)
    difficulty_rating: int = Field(ge=1, le=5)
    week_number: int = Field(ge=1)


class ProgressAdjustment(BaseModel):
    recommendation: str     # "maintain" | "reduce_intensity" | "add_recovery" | "progress_gradually"
    reasoning: str
    next_week_modifications: list[str]


# ---------------------------------------------------------------------------
# Final Workflow Result
# ---------------------------------------------------------------------------

class WorkflowResult(BaseModel):
    request_id: str
    workflow_status: str        # "completed" | "safety_blocked" | "redirected" | "normalisation_failed" | "review_failed"
    execution_mode: str = "live"  # "mock" | "live"
    safety_guidance: Optional[SafetyGuidanceResponse] = None
    fitness_plan: Optional[GeneratedFitnessPlan] = None
    review_result: Optional[PlanReviewResult] = None
    trace_events: list[dict] = Field(default_factory=list)

